name: Deploy main branch

on:
  push:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install JSON validator
        run: |
          wget https://github.com/neilpa/yajsv/releases/download/v1.4.0/yajsv.linux.amd64
          chmod +x ./yajsv.linux.amd64

      - name: Validate JSON
        run: |
          ./yajsv.linux.amd64 -s schema/stashes.schema.json ui/stashes.json

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Node modules
        run: npm install

      - name: Check formatting
        run: npx prettier --check .

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Node modules
        working-directory: ui
        run: npm install

      - name: Build
        working-directory: ui
        run: npm run build

      - name: Copy JSON files
        run: |
          jq -c . < ui/stashes.json > /tmp/stashes.json
          cp /tmp/stashes.json ui/dist
          cp ui/w3w.png ui/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ui/dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [validate, test, build]
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ui/dist

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::574363388371:role/HBTHalloweenChallengeCICDRole
          aws-region: eu-west-1

      - name: S3 Sync
        run: aws s3 sync ./ui/dist s3://halloween2023.hbt.ockenden.io
